SELECT * FROM EMPLOYEE;

--CURSOR WITHOUT VARIABLE.

DECLARE MYCURSOR CURSOR SCROLL FOR SELECT * FROM EMPLOYEE
OPEN MYCURSOR
FETCH FIRST FROM MYCURSOR
FETCH NEXT FROM MYCURSOR
FETCH LAST FROM MYCURSOR
FETCH PRIOR FROM MYCURSOR
FETCH ABSOLUTE 6 FROM MYCURSOR
FETCH RELATIVE 4 FROM MYCURSOR
FETCH RELATIVE -3 FROM MYCURSOR
CLOSE MYCURSOR
DEALLOCATE MYCURSOR

--CURSOR WITH VARIABLE.

DECLARE MYCURSOR CURSOR SCROLL FOR SELECT ID,FIRST_NAME,LAST_NAME,GENDER FROM EMPLOYEE
DECLARE @ID INT,@FNAME VARCHAR(50),@LNAME VARCHAR(50),@GENDER VARCHAR(10)
OPEN MYCURSOR
FETCH FIRST FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

PRINT '--------------------------------------------------------------------------------------------------------------------------'

FETCH NEXT FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

PRINT '--------------------------------------------------------------------------------------------------------------------------------'

FETCH LAST FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

PRINT '----------------------------------------------------------------------------------------------------------------------------------'

FETCH PRIOR FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

PRINT '-------------------------------------------------------------------------------------------------------------------------------------------'

FETCH ABSOLUTE 5 FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

PRINT '----------------------------------------------------------------------------------------------------------------------------------'

FETCH RELATIVE 5 FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

PRINT '-----------------------------------------------------------------------------------------------------------------------------------'

FETCH RELATIVE -2 FROM MYCURSOR INTO @ID,@FNAME,@LNAME,@GENDER
PRINT 'EMPLOYEE ID IS: '+ ' '+ CAST(@ID AS VARCHAR(10)) + ' ' +
'EMPLOYEE FIRSTNAME IS: '+' '+ @FNAME +' ' +
'EMPLOYEE LASTNAME IS: '+' '+ @LNAME +' ' +
'EMPLOYEE GENDER IS: '+' '+ @GENDER 

CLOSE MYCURSOR
DEALLOCATE MYCURSOR


BEGIN
    DECLARE @EID INT;
    DECLARE @EFNAME VARCHAR(50);
	DECLARE @ACTIVE BIT;
	DECLARE @DID INT;
	DECLARE EMPCURSOR CURSOR SCROLL FOR SELECT ID,FIRST_NAME,IS_ACTIVE,DEPARTMENT_ID FROM EMPLOYEE WHERE STATE = 'U.P.';
	OPEN EMPCURSOR
	FETCH NEXT FROM EMPCURSOR INTO @EID,@EFNAME,@ACTIVE,@DID
	WHILE @@FETCH_STATUS=0
	BEGIN
	    PRINT CAST(@EID AS VARCHAR(50))
	    PRINT @EFNAME
	    PRINT @ACTIVE
	    PRINT @DID
		FETCH NEXT FROM EMPCURSOR INTO @EID,@EFNAME,@ACTIVE,@DID
	END
	CLOSE EMPCURSOR
	DEALLOCATE EMPCURSOR
END;

SELECT * FROM PAYMENT;

BEGIN
    DECLARE @AMOUNT INT;
	DECLARE @MODE VARCHAR(50);
	DECLARE @PAYDATE DATE;
	DECLARE PAYMENTCURSOR CURSOR SCROLL FOR SELECT AMOUNT,MODE,PAYMENT_DATE FROM PAYMENT WHERE MODE = 'CASH';
	OPEN PAYMENTCURSOR
	FETCH NEXT FROM PAYMENTCURSOR INTO @AMOUNT,@MODE,@PAYDATE
	WHILE @@FETCH_STATUS=0
	BEGIN 
	   PRINT 'AMOUNT :' + ' ' + CAST(@AMOUNT AS VARCHAR(10))
	   PRINT 'MODE :' + ' ' + @MODE
	   PRINT 'PAYMENTDATE :'+ ' ' + CAST(@PAYDATE AS VARCHAR(100))
	   FETCH NEXT FROM PAYMENTCURSOR INTO @AMOUNT,@MODE,@PAYDATE
	END
    CLOSE PAYMENTCURSOR
	DEALLOCATE PAYMENTCURSOR
END;

