SELECT * FROM SALESLT.ADDRESS;

CREATE FUNCTION FN_ADDRESS()
RETURNS TABLE
AS
RETURN(SELECT * FROM SALESLT.ADDRESS WHERE CITY = 'BOTHELL');

SELECT * FROM FN_ADDRESS();

SELECT * FROM DBO.FN_ADDRESS();

CREATE FUNCTION FN_ADDRESS1(@POSTALCODE AS NVARCHAR(50))
RETURNS TABLE
AS 
RETURN(SELECT * FROM SALESLT.ADDRESS WHERE POSTALCODE = @POSTALCODE)

SELECT * FROM FN_ADDRESS1('98011');

SELECT * FROM FN_ADDRESS1('M4B 1V7');

SELECT * FROM SALESLT.CUSTOMER;

SELECT * FROM SALESLT.ADDRESS;

CREATE FUNCTION FN_CUSTADD(@CUSTID AS INT)
RETURNS TABLE
AS
RETURN (SELECT * FROM SALESLT.CUSTOMER WHERE CUSTOMERID <= @CUSTID);

SELECT * FROM DBO.FN_CUSTADD(58);

SELECT * FROM DBO.FN_CUSTADD(58) AS A
INNER JOIN SALESLT.ADDRESS B
ON A.CUSTOMERID = B.ADDRESSID;

CREATE FUNCTION FN_LASTNM(@LASTNAME AS VARCHAR(30))
RETURNS @MYTABLE1 TABLE(CUST_ID INT,CUST_FNAME VARCHAR(30),CUST_LNAME VARCHAR(30))
AS
BEGIN
INSERT INTO @MYTABLE1
SELECT CUSTOMERID,FIRSTNAME,LASTNAME FROM SALESLT.CUSTOMER WHERE LASTNAME=@LASTNAME
RETURN
END

SELECT * FROM DBO.FN_LASTNM('CARROLL');

SELECT * FROM SALESLT.PRODUCT;

CREATE FUNCTION FN_PDT(@PRODUCTMODELID AS INT)
RETURNS INT
AS
BEGIN
RETURN (@PRODUCTMODELID)
END

SELECT DBO.FN_PDT(33);


