CREATE TABLE EMPLOYEE(ID INT, FIRST_NAME VARCHAR(50),LAST_NAME VARCHAR(50),EMAIL VARCHAR(50),GENDER VARCHAR(20),IS_ACTIVE BIT);

INSERT INTO EMPLOYEE VALUES(1,'AMAN','DHAKRE','amandhakre@gmail.com','MALE',1);
INSERT INTO EMPLOYEE VALUES(2,'GAURAV','SINGH','gaurav699@gmail.com','MALE',1);
INSERT INTO EMPLOYEE VALUES(3,'AKANSHA','SHARMA','aksh88@gmail.com','FEMALE',0);
INSERT INTO EMPLOYEE VALUES(4,'ROHIT','GUPTA','rohit908@gmail.com','MALE',0);
INSERT INTO EMPLOYEE VALUES(5,'NISHA','SINGH','nishasingh33@gmail.com','FEMALE',1);
INSERT INTO EMPLOYEE VALUES(6,'ABHISHEK','BHARGAV','abhibhargav@gmail.com','MALE',0);
INSERT INTO EMPLOYEE VALUES(7,'ANJALI','AGARWAL','agarwalanjali@gmail.com','FEMALE',0);
INSERT INTO EMPLOYEE VALUES(8,'PRIYA','DHIMAN','pd77@gmail.com','FEMALE',0);
INSERT INTO EMPLOYEE VALUES(9,'PRIYANSHU','PRATAP','priyanshu26@gmail.com','MALE',1);
INSERT INTO EMPLOYEE VALUES(10,'VISHAL','PANDEY','vishalpd@gmail.com','MALE',0);
INSERT INTO EMPLOYEE VALUES(11,'MANJRI','JADOUN','jadounmanjri@gmail.com','FEMALE',1);
INSERT INTO EMPLOYEE VALUES(12,'RAJESH','PAL','rajeshp21@gmail.com','MALE',0);
INSERT INTO EMPLOYEE VALUES(13,'TANU','VERMA','tanu675@gmail.com','FEMALE',1);
INSERT INTO EMPLOYEE VALUES(14,'SHARDUL','THAKUR','thakurshardul@gmail.com','MALE',1);

SELECT * FROM EMPLOYEE;

CREATE PROCEDURE GETEMPLOYEE
(
@GENDER VARCHAR(20),
@IS_ACTIVE BIT
)
AS
BEGIN
 SELECT ID,
 FIRST_NAME,
 LAST_NAME,
 EMAIL,
 GENDER,
 IS_ACTIVE
 FROM EMPLOYEE
 WHERE GENDER = @GENDER AND IS_ACTIVE = @IS_ACTIVE
END

EXEC GETEMPLOYEE 'MALE',0;
EXEC GETEMPLOYEE 'MALE',1;
EXEC GETEMPLOYEE 'FEMALE',0;
EXEC GETEMPLOYEE 'FEMALE',1;
